fixup! UPSTREAM: bpf, sockmap: Fix sk->sk_forward_alloc warn_on in sk_stream_kill_queues
'prot->destroy', which is undefined in this kernel.
Use 'orig->destroy' instead.

Fixes:
../net/core/skmsg.c:493:25: error: use of undeclared identifier 'prot'
493 |                 psock->saved_destroy = prot->destroy;
    |

Change-Id: I59c94fd5abe40e52c3698e4fb66950517946c0b6